// Code generated by mockery v2.20.0. DO NOT EDIT.

package adaptermock

import (
	entity "github.com/Kin-dza-dzaa/flash_cards_api/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// Tranlsator is an autogenerated mock type for the Tranlsator type
type Tranlsator struct {
	mock.Mock
}

// Translate provides a mock function with given fields: word
func (_m *Tranlsator) Translate(word string) (*entity.WordTrans, error) {
	ret := _m.Called(word)

	var r0 *entity.WordTrans
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.WordTrans, error)); ok {
		return rf(word)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.WordTrans); ok {
		r0 = rf(word)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.WordTrans)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(word)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewTranlsator interface {
	mock.TestingT
	Cleanup(func())
}

// NewTranlsator creates a new instance of tranlsator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTranlsator(t mockConstructorTestingTnewTranlsator) *Tranlsator {
	mock := &Tranlsator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
