logger:
  log_level: "debug"

http:
  host: "0.0.0.0"
  port: ":8000"
  read_timeout: 5s 
  write_timeout: 5s 
  shutdown_timeout: 10s
  rate_limit: 100
  rate_window: 30s
  allowed_origins:
    - http://localhost:3000
    - http://localhost

postgres:
  max_pool_size: 5

dictionaryapi:
  url: https://translate.google.com/_/TranslateWebserverUi/data/batchexecute
  default_src_lang: en
  default_trgt_lang: ru
